### ISSUE TITLE
Investigate TLM incompatibility

### ISSUE THREAD

**Issue by Jameskmonger** [Jameskmonger/CSL-ShowCommuterDestination#3]
https://github.com/klyte45/TransportLinesManager/issues/195

**Comment by MatthewForrester** [comment]
Thank you for responding!

If you are able to make your mod compatible with TLM as well, that would be great. It offers more features than IPT2.

Drop me a note here if you would like me to test the beta.

**Comment by Finwickle** [comment]
Any news on this?

**Comment by Jameskmonger** [comment]
Sorry for the late response

I have looked into this and I can no longer see the "Line Incomplete" issue which was reported by @MatthewForrester when running the latest Workshop releases of Commuter Destination and TLM.

The only issue I can see now is:

- When **Commuter Destination** and **TLM** are enabled, clicking on the "button" for a stop will close the TLM window. Without Commuter Destination, the TLM window stays open.

This seems less severe than originally reported, but as there are still ~80k users of TLM, I'll try to investigate a fix.

**Comment by Jameskmonger** [comment]
The fix was quite easy, this should now be solved. **Commuter Destination 0.4.1** should work fine with **TLM 14.4**

Please raise a new issue if that's not the case
