### ISSUE TITLE
Error when IPT2 is not installed

### ISSUE THREAD

**Issue by Vectorial1024** [Jameskmonger/CSL-ShowCommuterDestination#4]
Might be similar to #3, but when I use this with TLM, I discover that this mod is trying to open IPT2 panels. This causes an error because I did not install IPT2.

**Comment by Jameskmonger** [comment]
Hi @Vectorial1024, thanks for reporting this (and apologies for the late response)

Commuter Destination will attempt to open IPT2 panels, but this is only an optional integration. You will receive an error in ModTools etc atm but the mod should function correctly regardless.

My local testing without IPT2 shows this to be the case. Can you confirm whether you are still experiencing issues?

**Comment by Jameskmonger** [comment]
I have raised a PR to fix this in #8 - Commuter Destination will no longer attempt to display the IPT2 panel if it isn't enabled.

**Comment by Vectorial1024** [comment]
Hi there again!

Indeed I was using ModTools to help with debugging my mods, and I have just checked again, this error no longer occurs. I can now click on stops to see the destinations and there are not IPT2-related errors.

Many thanks for the fix!
